### PR TITLE
Deal with frozen string literals

### LINKED ISSUE #2619: Passenger does not work with ruby frozen-string-literal
Ruby is moving toward having literal strings frozen by default[[1](https://bugs.ruby-lang.org/issues/20205)][[2](https://www.prateekcodes.dev/ruby-34-frozen-string-literals-rails-upgrade-guide/)]. Currently passenger has many instances where it mutates a literal string. This will break in future version of ruby where literal strings are frozen, and currently breaks apps that try and run with frozen-string-literal enabled.

I tested this with the latest version of passenger (6.0.27) with rails 7.1.5 on ruby 3.1.3 and rails 8.0.2 on ruby 3.2.2. I am on Mac OSX 15.4.

I found a bunch of cases where string literals were mutated, and started to [try and fix them](https://github.com/phusion/passenger/commit/7bf30419dcde8f3d9333d39be70d97a0b340b3fa). But I was unable to get very far since I couldn't get the dev environment setup for passenger. Hopefully this helps someone else get started.

### SETUP

Generate a new rails app:
`rails new my_app`
`cd my_app`

Add passenger to the Gemfile:
`gem "passenger", "~> 6.0.27", require: "phusion_passenger/rack_handler"`

Bundle install to install passenge:
`bundle install`

Run passenger with frozen-string-literal enabled:
`RUBYOPT="--enable=frozen_string_literal" bundle exec passenger start`

### OBSERVED BEHAVIOR
Passenger fails to start with a `FrozenError` in the passenger code.

```
bundler: failed to load command: passenger (/Users/steven.boyd/.asdf/installs/ruby/3.2.2/bin/passenger)
/Users/steven.boyd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/passenger-6.0.27/src/ruby_supportlib/phusion_passenger.rb:192:in `block in <module:PhusionPassenger>': can't modify frozen String: "" (FrozenError)
	from /Users/steven.boyd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/passenger-6.0.27/src/ruby_supportlib/phusion_passenger.rb:191:in `each'
	from /Users/steven.boyd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/passenger-6.0.27/src/ruby_supportlib/phusion_passenger.rb:191:in `<module:PhusionPassenger>'
	from /Users/steven.boyd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/passenger-6.0.27/src/ruby_supportlib/phusion_passenger.rb:26:in `<top (required)>'
	from <internal:/Users/steven.boyd/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/steven.boyd/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/steven.boyd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/passenger-6.0.27/bin/passenger:33:in `<top (required)>'
	from /Users/steven.boyd/.asdf/installs/ruby/3.2.2/bin/passenger:25:in `load'
	from /Users/steven.boyd/.asdf/installs/ruby/3.2.2/bin/passenger:25:in `<top (required)>'
	from /Users/steven.boyd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/steven.boyd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/steven.boyd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/steven.boyd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/cli.rb:491:in `exec'
	from /Users/steven.boyd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/steven.boyd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/steven.boyd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/steven.boyd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/steven.boyd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/steven.boyd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/cli.rb:28:in `start'
	from /Users/steven.boyd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/exe/bundle:45:in `block in <top (required)>'
	from /Users/steven.boyd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/steven.boyd/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/exe/bundle:33:in `<top (required)>'
	from /Users/steven.boyd/.asdf/installs/ruby/3.2.2/bin/bundle:25:in `load'
	from /Users/steven.boyd/.asdf/installs/ruby/3.2.2/bin/bundle:25:in `<main>'
```

### DESIRED BEHAVIOR

Passenger boots up and works with frozen-string-literal enabled.

### PR DESCRIPTION
**Pull request by CamJN**
In future Ruby is going to encourage frozen string literals

### CODE REVIEW

**Comment by gremz** [comment]
@CamJN just wanted to see if there is perhaps a timeline to merge this for the next release? Thanks!

File: src/ruby_supportlib/phusion_passenger/vendor/crash_watch/gdb_controller.rb [hunk 1]
```diff
@@ -63,7 +63,7 @@ def execute(command_string, timeout = nil)
       @in.puts(command_string)
       @in.puts("echo \\n#{END_OF_RESPONSE_MARKER}\\n")
       done = false
-      result = ""
+      result = String.new
```
Comment (byroot) [inline src/ruby_supportlib/phusion_passenger/vendor/crash_watch/gdb_controller.rb:66]: It may or may not matter in this case, but note that `String.new` isn't equivalent here, as it create a binary string:

```ruby
>> String.new.encoding
=> #<Encoding:BINARY (ASCII-8BIT)>
```

To get a mutable string the idiomatic way is:

```ruby
result = +""
```

For Ruby 2.4+.

For older rubies, you can just do `"".dup`, or if really you prefer `String.new`, then `String.new(encoding:: Encoding::UTF_8)`.

File: dev/ruby_server.rb [hunk 2]
```diff
@@ -135,7 +135,7 @@ def start_thread
   def handle_next_client(forward_connection)
     client = @server.accept
     begin
-      buffer = "".force_encoding("binary")
+      buffer = String.new(encoding: Encoding::BINARY)
```
Comment (byroot) [inline dev/ruby_server.rb:138]: As mentioned in the previous comment, BINARY encoding is the default for `String.new`. 

But there is also the `"".b` shorthand to get a mutable binary buffer.
