### PR TITLE
Fix support for Bundler restarts

### LINKED ISSUE #2567: Passenger will not preload rack app after Bundler 2.5.11, if correct bundler is not installed
## Issue report

**Please try with the newest version of Passenger to avoid issues that have already been fixed**

**Question 1: What is the problem?**

I don't know what changed between RubyGems 3.5.11 and 3.5.12. But from 3.5.12 onwards, passenger will not load any rack app, and I've tested most versions, including the latest, 3.5.20. If I switch back to 3.5.11, everything starts working again. 

RubyGems v3.5.12 +
```
App output: /usr/local/bin/ruby: No such file or directory -- Passenger AppPreloader: /app/path (LoadError)
```

Note: that the app directory had a Gemfile (and lock) in it, but I rewrote the config.ru to remove rails and the app it self from my test.

config.ru:
```
run do |env|
  [200, {}, ["Hello World"]]
end
```

Your answer:

**Question 2: Passenger version and integration mode**:
- open source 6.0.23 standalone

Your answer:

**Question 3: OS or Linux distro, platform (including version)**:
- Debian GNU/Linux 12 (bookworm), x86_64  and aarch64

Your answer:

**Question 4: Passenger installation method**:

Your answer:
- [ ] RubyGems + Gemfile
- [x] RubyGems, no Gemfile
- [ ] Phusion APT repo
- [ ] Phusion YUM repo
- [ ] OS X Homebrew
- [ ] source tarball
- [ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
- Ruby 3.3.5, Rails 7.1.x but in my tests I used an hello world rackup app.

Your answer:

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- Docker-based on the official ruby image

### LINKED ISSUE #2577: Passenger AppPreloader reports existing ruby executables as non existing when BUNDLED WITH in Gemfile.lock differs from pre-installed
Rails Apps based on this image are not starting up showing "We're sorry, but something went wrong".

`/var/log/nginx/error.log` shows:

```
App 1977 output: /usr/local/rvm/rubies/ruby-3.1.5/bin/ruby: No such file or directory -- Passenger AppPreloader: /home/app/webapp (LoadError)
[ E 2024-06-18 00:20:11.9001 77/T29 age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/app/webapp: The application process exited prematurely.
  Error ID: 4b6cb0aa
  Error details saved to: /tmp/passenger-error-O6tEuV.html

[ E 2024-06-18 00:20:11.9014 77/Tr age/Cor/Con/CheckoutSession.cpp:281 ]: [Client 10-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 4b6cb0aa. Please see earlier logs for details about the error.
```

but the file actually exists:

```bash
root@05b1edfe5a34:/home/app/webapp# ls -la /usr/local/rvm/rubies/ruby-3.1.5/bin/ruby
-rwxrwxr-x 1 root root 215920 May 17 10:24 /usr/local/rvm/rubies/ruby-3.1.5/bin/ruby
```

and  is really executable:

```bash
root@05b1edfe5a34:/home/app/webapp# /usr/local/rvm/rubies/ruby-3.1.5/bin/ruby --version
ruby 3.1.5p252 (2024-04-23 revision 1945f8dc0e) [x86_64-linux]
```

This happens for images based on
* phusion/passenger-ruby31:3.0.4
* phusion/passenger-ruby31:3.0.5
* phusion/passenger-ruby31:3.0.6 / latest, both when using already-installed 3.1.5 and also when installing ruby-3.1.4 via rvm
* phusion/passenger-ruby32 (latest) when using ruby 3.2.2 (i.e. NOT the one which comes with the image but installing it via rvm during docker build.) and also with ruby 3.2.4 (the one which comes with the image)

There's no issue with the latest docker/passenger-ruby33 image when using the ruby which comes with the image. I didn't try installing a different version via rvm.

I first noticed this last Friday's nightly CI run (i.e. since 3.0.6 has been released).

It also happens for images built before which worked before but where container is recreated, i.e. already existing images stop working.

Nginx config sets `passenger_ruby /usr/bin/ruby;` but this is just a wrapper forwarding to /usr/local/rvm/wrappers/default/ruby which then references `/usr/local/rvm/gems/ruby-3.1.5/environment` which contains:

```
export PATH="/usr/local/rvm/gems/ruby-3.1.5/bin:/usr/local/rvm/gems/ruby-3.1.5@global/bin:/usr/local/rvm/rubies/ruby-3.1.5/bin:$PATH"
export GEM_HOME='/usr/local/rvm/gems/ruby-3.1.5'
export GEM_PATH='/usr/local/rvm/gems/ruby-3.1.5:/usr/local/rvm/gems/ruby-3.1.5@global'
export MY_RUBY_HOME='/usr/local/rvm/rubies/ruby-3.1.5'
export IRBRC='/usr/local/rvm/rubies/ruby-3.1.5/.irbrc'
unset MAGLEV_HOME
unset RBXOPT
export RUBY_VERSION='ruby-3.1.5'
```

It still doesn't work when setting `passenger_ruby /usr/local/rvm/rubies/ruby-3.1.5/bin/ruby;`

Even though I tested quite a few different combinations of image versions and ruby versions, I still don't know where the issue comes from. Newly created containers from images built `FROM phusion/passenger-ruby31` before last Thursday were working before but  are now **also broken** once recreated.

### PR DESCRIPTION
**Pull request by CamJN**
By using `Process.setproctitle` instead of renaming `$0`.

See [original problem description](https://github.com/phusion/passenger/issues/2577#issuecomment-2525105583).

### CODE REVIEW

File: src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb [hunk 1]
```diff
@@ -210,6 +210,17 @@ def run_load_path_setup_code(options)
...
+        # Bundler 2.5.12+ throws a hissy fit if you don't have the
+        # version of bundler installed with which the Gemfile.lock was
+        # created. This causes extremely inscrutible error messages such
+        # as `/usr/bin/ruby doesn't exist`, so we cause RubyGems to raise
+        # an intelligible error here instead.
+        if File.exist?('Gemfile.lock')
+          lockfile_contents = File.read('Gemfile.lock').lines.map(&:strip)
+          index = lockfile_contents.index 'BUNDLED WITH'
+          bundler_version = lockfile_contents[index + 1] unless index.nil?
+          found = Gem::Specification.find_by_name('bundler', "= #{bundler_version}") unless bundler_version.nil?
```
Comment (FooBarWidget) [inline src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:222]: It appears you're not doing anything with `found`. Does the mere act of calling `Gem::Specification.find_by_name` fix this issue?

**Comment by FooBarWidget** [comment]
This is a good workaround for #2577 in order to make the error more legible, but it's ultimately not a fix. `bundle exec` on the CLI works, as does the 'direct' spawn method, so we need to figure out what's *really* going on here.

**Comment by FooBarWidget** [comment]
@CamJN I have analyzed the root cause and identified a better fix strategy. Please see:
https://github.com/phusion/passenger/issues/2577#issuecomment-2525086988
https://github.com/phusion/passenger/issues/2577#issuecomment-2525105583

**Comment by CamJN** [comment]
We can just do what puma does, and use `Process.setproctitle`, then it doesn't matter what bundler decides to do, or what version users are running. Works back to ~ Ruby 2.1.

**Review by FooBarWidget — APPROVED** [review]
